update C0DE-OF-CONDUCT.md
githubevents/universe2020 pull request #2
Opened 2020-12-08 17:09 UTC by domitechnshimba

update C0DE-OF-CONDUCT.md

Note that I have made a few changes to MD

2020-12-08 17:47 UTC, Flaxxas commented on README.md
> +Visit the Officical Weboste: [https://githubuniverse.com](https://githubuniverse.com/)
```suggestion
Visit the official website: [https://githubuniverse.com](https://githubuniverse.com/)
```

2020-12-08 18:13 UTC, xetra11 commented
I feel better now being on Github

2020-12-08 19:15 UTC, Lubo-mir requested changes

2020-12-08 19:15 UTC, Lubo-mir commented on README.md
> +Visit the Officical Weboste: [https://githubuniverse.com](https://githubuniverse.com/)
```suggestion
Visit the Officical Website: [githubuniverse.com](https://githubuniverse.com/)
```
Protocol and path prefix are not necessary to display 😉

2020-12-08 21:43 UTC, HPaulson requested changes

2020-12-08 21:43 UTC, HPaulson commented on README.md
> +Visit the Officical Weboste: [https://githubuniverse.com](https://githubuniverse.com/)
Why not just use a hyperlink here?
```suggestion
Visit the [Official Website](https://githubuniverse.com/)
```

2020-12-09 13:01 UTC, martinwoodward commented
Thanks folks - probably just leave this one as is for now but appreciate you pointing out the potential fixes.

2020-12-09 13:01 UTC, closed without merging